[package]
name = "rusty_style"
version = "0.1.2"
authors = ["edward elton"]
edition = "2021"
description = "Rusty Style is a library for styling text in the terminal."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
