[package]
name = "rusty_style"
version = "0.1.0"
authors=["edward elton"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
